name: Shard CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  LintAndTest:
    strategy:
      matrix:
        crystal_version:
          - 0.35.1
          - 0.36.1
          - latest
          - nightly

    runs-on: ubuntu-latest

    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine

    steps:
      - name: Check format
        run: crystal tool format --check

      - name: Run tests
        run: crystal spec
